"use client";

import { useState } from "react";

import { Card, State, useApi } from "@/components/ui";
import { API_BASE } from "@/lib/api";

interface Report {
  name: string;
  markdown: string;
  data: Record<string, unknown> | null;
}

const TABS: [string, string][] = [
  ["backtest", "Walk-forward backtest"],
  ["forecast_eval", "Forecast evaluation & calibration"],
  ["optimizer_benchmark", "Optimiser benchmark"],
  ["price_change", "Price-change model"],
  ["baselines", "Baselines"],
  ["rate_shrinkage", "Rate shrinkage"],
  ["feature_importance", "Feature importance"],
  ["ensemble_conformal", "Ensemble & conformal (P1)"],
];

const FIGS: Record<string, string[]> = {
  forecast_eval: ["forecast_reliability_6plus.svg", "forecast_reliability_start.svg", "forecast_pit.svg"],
  price_change: ["price_reliability.svg"],
  backtest: ["backtest_cumulative_2024-25.svg", "backtest_cumulative_2025-26.svg"],
};

export default function BacktestLab() {
  const [tab, setTab] = useState("backtest");
  const rep = useApi<Report>(`/reports/${tab}`, [tab]);
  return (
    <>
      <h1>Backtest Lab</h1>
      <p className="small">Published, reproducible reports (generated by <code>ml/experiments/*</code>; successes and failures included).</p>
      <div className="row" style={{ marginBottom: 12 }}>
        {TABS.map(([k, label]) => (
          <button key={k} className={tab === k ? "" : "secondary"} onClick={() => setTab(k)}>{label}</button>
        ))}
      </div>
      <Card testId="report" wide>
        <State loading={rep.loading} error={rep.error} />
        <div className="row">
          {(FIGS[tab] ?? []).map((f) => (
            // eslint-disable-next-line @next/next/no-img-element
            <img key={f} src={`${API_BASE}/api/v1/reports/figures/${f}`} alt={f} style={{ background: "#fff", borderRadius: 6, maxWidth: 420 }} />
          ))}
        </div>
        {rep.data ? <pre className="md">{rep.data.markdown}</pre> : null}
      </Card>
    </>
  );
}
