"use client";

import { useState } from "react";

import { Markdown } from "@/components/markdown";
import { Card, State, useApi } from "@/components/ui";
import { apiUrl } from "@/lib/api";

interface Report {
  name: string;
  markdown: string;
  data: Record<string, unknown> | null;
}

const TABS: [string, string][] = [
  ["backtest", "Walk-forward backtest"],
  ["forecast_eval", "Forecast evaluation & calibration"],
  ["optimizer_benchmark", "Optimiser benchmark"],
  ["price_change", "Price-change model"],
  ["baselines", "Baselines"],
  ["rate_shrinkage", "Rate shrinkage"],
  ["feature_importance", "Feature importance"],
  ["ensemble_conformal", "Ensemble & conformal (P1)"],
];

export default function BacktestLab() {
  const [tab, setTab] = useState("backtest");
  const rep = useApi<Report>(`/reports/${tab}`, [tab]);
  return (
    <>
      <h1>Backtest Lab</h1>
      <p className="small">Published, reproducible reports (generated by <code>ml/experiments/*</code>; successes and failures included).</p>
      <div className="row" style={{ marginBottom: 12 }}>
        {TABS.map(([k, label]) => (
          <button key={k} className={tab === k ? "" : "secondary"} onClick={() => setTab(k)}>{label}</button>
        ))}
      </div>
      <Card testId="report" wide>
        <State loading={rep.loading} error={rep.error} />
        {/* figures are shown where the report references them (no separate list to drift) */}
        {rep.data ? <Markdown text={rep.data.markdown} figure={(f) => apiUrl(`/reports/figures/${encodeURIComponent(f)}`)} /> : null}
      </Card>
    </>
  );
}
