"""accounts, squad analyses, product events

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-10 08:54:14.659254+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analytics_opt_out', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('invites',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by', sa.String(length=32), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['redeemed_by'], ['users.id'], name=op.f('fk_invites_redeemed_by_users')),
    sa.PrimaryKeyConstraint('code_hash', name=op.f('pk_invites'))
    )
    op.create_table('product_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('props_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_events'))
    )
    op.create_index('ix_product_events_created_at', 'product_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_events_event'), 'product_events', ['event'], unique=False)
    op.create_index(op.f('ix_product_events_user_id'), 'product_events', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_managers',
    sa.Column('manager_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_managers_user_id_users')),
    sa.PrimaryKeyConstraint('manager_key', name=op.f('pk_user_managers'))
    )
    op.create_index(op.f('ix_user_managers_user_id'), 'user_managers', ['user_id'], unique=False)
    op.create_table('squad_analyses',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('manager_key', sa.String(length=64), nullable=False),
    sa.Column('state_id', sa.String(length=80), nullable=False),
    sa.Column('data_snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('forecast_key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['manager_state.id'], name=op.f('fk_squad_analyses_state_id_manager_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squad_analyses')),
    sa.UniqueConstraint('manager_key', 'state_id', 'data_snapshot_id', 'forecast_key', 'version', name=op.f('uq_squad_analyses_manager_key_state_id_data_snapshot_id_forecast_key_version'))
    )
    op.create_index(op.f('ix_squad_analyses_manager_key'), 'squad_analyses', ['manager_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squad_analyses_manager_key'), table_name='squad_analyses')
    op.drop_table('squad_analyses')
    op.drop_index(op.f('ix_user_managers_user_id'), table_name='user_managers')
    op.drop_table('user_managers')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_product_events_user_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_event'), table_name='product_events')
    op.drop_index('ix_product_events_created_at', table_name='product_events')
    op.drop_table('product_events')
    op.drop_table('invites')
    op.drop_table('users')
    # ### end Alembic commands ###
