"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 14:22:42.077223+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_table('artifact_blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sha256', name=op.f('pk_artifact_blobs'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('season', sa.String(length=7), nullable=False),
    sa.Column('from_gw', sa.SmallInteger(), nullable=False),
    sa.Column('to_gw', sa.SmallInteger(), nullable=False),
    sa.Column('cutoff_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('benchmark', sa.String(length=64), nullable=False),
    sa.Column('model_version', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('data_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifacts_uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_runs'))
    )
    op.create_table('data_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("status in ('running','succeeded','failed','quarantined')", name=op.f('ck_data_jobs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_jobs'))
    )
    op.create_index(op.f('ix_data_jobs_job_type'), 'data_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_data_jobs_source'), 'data_jobs', ['source'], unique=False)
    op.create_index(op.f('ix_data_jobs_status'), 'data_jobs', ['status'], unique=False)
    op.create_table('data_snapshots',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('source_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_snapshots'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_ref', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_request_hash'), 'jobs', ['request_hash'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('manager_settings',
    sa.Column('manager_key', sa.String(length=64), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('manager_key', name=op.f('pk_manager_settings'))
    )
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=True),
    sa.Column('training_window', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('parent_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('candidate','approved','production','rejected','retired')", name=op.f('ck_model_registry_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_registry')),
    sa.UniqueConstraint('model_name', 'version', name=op.f('uq_model_registry_model_name_version'))
    )
    op.create_index(op.f('ix_model_registry_model_name'), 'model_registry', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_registry_status'), 'model_registry', ['status'], unique=False)
    op.create_index('uq_model_registry_one_production', 'model_registry', ['model_name'], unique=True, postgresql_where="status = 'production'")
    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('manager_key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('materiality', sa.Float(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('manager_key', 'dedupe_key', name=op.f('uq_notifications_manager_key_dedupe_key'))
    )
    op.create_index(op.f('ix_notifications_manager_key'), 'notifications', ['manager_key'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_code', sa.String(length=7), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('schema_version', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('season_code', name=op.f('uq_seasons_season_code'))
    )
    op.create_table('backtest_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.String(length=80), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_accessed_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('predicted_points', sa.Float(), nullable=False),
    sa.Column('actual_points', sa.Float(), nullable=False),
    sa.Column('hit_cost', sa.SmallInteger(), nullable=False),
    sa.Column('decision_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('max_accessed_available_at <= cutoff_at', name=op.f('ck_backtest_decisions_no_lookahead')),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], name=op.f('fk_backtest_decisions_backtest_id_backtest_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_decisions'))
    )
    op.create_index(op.f('ix_backtest_decisions_backtest_id'), 'backtest_decisions', ['backtest_id'], unique=False)
    op.create_table('data_quality_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('issue_code', sa.String(length=64), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.CheckConstraint("severity in ('info','warning','error','critical')", name=op.f('ck_data_quality_events_severity')),
    sa.ForeignKeyConstraint(['job_id'], ['data_jobs.id'], name=op.f('fk_data_quality_events_job_id_data_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_events'))
    )
    op.create_index(op.f('ix_data_quality_events_issue_code'), 'data_quality_events', ['issue_code'], unique=False)
    op.create_index(op.f('ix_data_quality_events_severity'), 'data_quality_events', ['severity'], unique=False)
    op.create_index(op.f('ix_data_quality_events_source'), 'data_quality_events', ['source'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('target_gw', sa.SmallInteger(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('data_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('max_source_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_source_available_at <= cutoff_at', name=op.f('ck_feature_snapshots_no_future_sources')),
    sa.ForeignKeyConstraint(['data_snapshot_id'], ['data_snapshots.id'], name=op.f('fk_feature_snapshots_data_snapshot_id_data_snapshots')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_feature_snapshots_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_snapshots'))
    )
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deadline_source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_gameweeks_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gameweeks')),
    sa.UniqueConstraint('season_id', 'gw', name=op.f('uq_gameweeks_season_id_gw'))
    )
    op.create_index(op.f('ix_gameweeks_season_id'), 'gameweeks', ['season_id'], unique=False)
    op.create_table('manager_chips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('chip_id', sa.String(length=32), nullable=False),
    sa.Column('chip_type', sa.String(length=32), nullable=False),
    sa.Column('half', sa.SmallInteger(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_gw', sa.SmallInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_manager_chips_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_chips')),
    sa.UniqueConstraint('manager_id', 'season_id', 'chip_id', name=op.f('uq_manager_chips_manager_id_season_id_chip_id'))
    )
    op.create_index(op.f('ix_manager_chips_manager_id'), 'manager_chips', ['manager_id'], unique=False)
    op.create_table('manager_state',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bank', sa.SmallInteger(), nullable=False),
    sa.Column('free_transfers', sa.SmallInteger(), nullable=False),
    sa.Column('overall_points', sa.Integer(), nullable=True),
    sa.Column('overall_rank', sa.BigInteger(), nullable=True),
    sa.Column('team_value', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_snapshot_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('free_transfers between 0 and 20', name=op.f('ck_manager_state_ft_range')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_manager_state_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_state'))
    )
    op.create_index(op.f('ix_manager_state_manager_id'), 'manager_state', ['manager_id'], unique=False)
    op.create_index(op.f('ix_manager_state_season_id'), 'manager_state', ['season_id'], unique=False)
    op.create_index(op.f('ix_manager_state_state_hash'), 'manager_state', ['state_hash'], unique=False)
    op.create_table('manager_transfers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('in_player_code', sa.Integer(), nullable=False),
    sa.Column('out_player_code', sa.Integer(), nullable=False),
    sa.Column('in_cost', sa.SmallInteger(), nullable=False),
    sa.Column('out_value', sa.SmallInteger(), nullable=False),
    sa.Column('cost', sa.SmallInteger(), nullable=False),
    sa.Column('free_or_hit', sa.String(length=8), nullable=False),
    sa.Column('made_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_manager_transfers_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_transfers')),
    sa.UniqueConstraint('manager_id', 'season_id', 'gw', 'in_player_code', 'out_player_code', name=op.f('uq_manager_transfers_manager_id_season_id_gw_in_player_code_out_player_code'))
    )
    op.create_index(op.f('ix_manager_transfers_manager_id'), 'manager_transfers', ['manager_id'], unique=False)
    op.create_table('news_signals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_code', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('structured_status', sa.String(length=32), nullable=False),
    sa.Column('chance_of_playing', sa.SmallInteger(), nullable=True),
    sa.Column('evidence_strength', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_news_signals_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_signals'))
    )
    op.create_index(op.f('ix_news_signals_player_code'), 'news_signals', ['player_code'], unique=False)
    op.create_index(op.f('ix_news_signals_season_id'), 'news_signals', ['season_id'], unique=False)
    op.create_table('raw_snapshots',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['data_jobs.id'], name=op.f('fk_raw_snapshots_job_id_data_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_snapshots')),
    sa.UniqueConstraint('source', 'resource', 'sha256', name=op.f('uq_raw_snapshots_source_resource_sha256'))
    )
    op.create_index(op.f('ix_raw_snapshots_sha256'), 'raw_snapshots', ['sha256'], unique=False)
    op.create_index(op.f('ix_raw_snapshots_source'), 'raw_snapshots', ['source'], unique=False)
    op.create_table('team_strength',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.Integer(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('attack_rating', sa.Float(), nullable=False),
    sa.Column('defence_rating', sa.Float(), nullable=False),
    sa.Column('attack_sd', sa.Float(), nullable=False),
    sa.Column('defence_sd', sa.Float(), nullable=False),
    sa.Column('home_advantage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_team_strength_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_strength')),
    sa.UniqueConstraint('season_id', 'team_code', 'cutoff_at', 'model_version', name=op.f('uq_team_strength_season_id_team_code_cutoff_at_model_version'))
    )
    op.create_index(op.f('ix_team_strength_season_id'), 'team_strength', ['season_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.String(length=4), nullable=False),
    sa.Column('strength_home', sa.Integer(), nullable=True),
    sa.Column('strength_away', sa.Integer(), nullable=True),
    sa.Column('strength_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_teams_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('season_id', 'code', name=op.f('uq_teams_season_id_code')),
    sa.UniqueConstraint('season_id', 'source_id', name=op.f('uq_teams_season_id_source_id'))
    )
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=False)
    op.create_index(op.f('ix_teams_season_id'), 'teams', ['season_id'], unique=False)
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=True),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('home_difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('away_difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('schedule_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('raw_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_fixtures_distinct_teams')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_fixtures_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_fixtures_home_team_id_teams')),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], name=op.f('fk_fixtures_raw_snapshot_id_raw_snapshots')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_fixtures_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixtures')),
    sa.UniqueConstraint('season_id', 'source_id', name=op.f('uq_fixtures_season_id_source_id'))
    )
    op.create_index(op.f('ix_fixtures_gw'), 'fixtures', ['gw'], unique=False)
    op.create_index(op.f('ix_fixtures_season_id'), 'fixtures', ['season_id'], unique=False)
    op.create_table('manager_squad',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.String(length=80), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('player_code', sa.Integer(), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('purchase_price', sa.SmallInteger(), nullable=False),
    sa.Column('selling_price', sa.SmallInteger(), nullable=False),
    sa.Column('is_starting', sa.Boolean(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_vice_captain', sa.Boolean(), nullable=False),
    sa.CheckConstraint('slot between 1 and 15', name=op.f('ck_manager_squad_slot_range')),
    sa.ForeignKeyConstraint(['state_id'], ['manager_state.id'], name=op.f('fk_manager_squad_state_id_manager_state'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_squad')),
    sa.UniqueConstraint('state_id', 'player_code', name=op.f('uq_manager_squad_state_id_player_code')),
    sa.UniqueConstraint('state_id', 'slot', name=op.f('uq_manager_squad_state_id_slot'))
    )
    op.create_index(op.f('ix_manager_squad_state_id'), 'manager_squad', ['state_id'], unique=False)
    op.create_table('player_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_code', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.SmallInteger(), nullable=False),
    sa.Column('form', sa.Float(), nullable=True),
    sa.Column('ownership', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('news', sa.Text(), nullable=True),
    sa.Column('news_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chance_of_playing_next_round', sa.SmallInteger(), nullable=True),
    sa.Column('expected_minutes', sa.Float(), nullable=True),
    sa.Column('set_piece_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('official_price_signal_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=False),
    sa.Column('raw_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], name=op.f('fk_player_snapshots_raw_snapshot_id_raw_snapshots')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_player_snapshots_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_snapshots')),
    sa.UniqueConstraint('season_id', 'player_code', 'captured_at', 'source', name=op.f('uq_player_snapshots_season_id_player_code_captured_at_source'))
    )
    op.create_index(op.f('ix_player_snapshots_player_code'), 'player_snapshots', ['player_code'], unique=False)
    op.create_index(op.f('ix_player_snapshots_season_id'), 'player_snapshots', ['season_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('web_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('price', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("position in ('GK','DEF','MID','FWD')", name=op.f('ck_players_position')),
    sa.CheckConstraint('price between 0 and 300', name=op.f('ck_players_price_range')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_players_season_id_seasons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('season_id', 'code', name=op.f('uq_players_season_id_code')),
    sa.UniqueConstraint('season_id', 'source_id', name=op.f('uq_players_season_id_source_id'))
    )
    op.create_index(op.f('ix_players_code'), 'players', ['code'], unique=False)
    op.create_index(op.f('ix_players_season_id'), 'players', ['season_id'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('prediction_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('base_gw', sa.SmallInteger(), nullable=False),
    sa.Column('horizon', sa.SmallInteger(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('simulation_seed', sa.BigInteger(), nullable=False),
    sa.Column('n_simulations', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('samples_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('degraded_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], name=op.f('fk_prediction_runs_feature_snapshot_id_feature_snapshots')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_prediction_runs_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_runs'))
    )
    op.create_table('record_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('natural_key', sa.String(length=255), nullable=False),
    sa.Column('old_hash', sa.String(length=64), nullable=False),
    sa.Column('new_hash', sa.String(length=64), nullable=False),
    sa.Column('old_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_snapshot_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], name=op.f('fk_record_revisions_raw_snapshot_id_raw_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_revisions'))
    )
    op.create_index(op.f('ix_record_revisions_natural_key'), 'record_revisions', ['natural_key'], unique=False)
    op.create_index(op.f('ix_record_revisions_table_name'), 'record_revisions', ['table_name'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_state_id', sa.String(length=80), nullable=True),
    sa.Column('prediction_run_id', sa.String(length=80), nullable=True),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('ruleset_hash', sa.String(length=64), nullable=False),
    sa.Column('solver', sa.String(length=32), nullable=False),
    sa.Column('solver_version', sa.String(length=32), nullable=True),
    sa.Column('objective_version', sa.String(length=64), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horizon', sa.SmallInteger(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('mip_gap', sa.Float(), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=False),
    sa.Column('solution_hash', sa.String(length=64), nullable=True),
    sa.Column('solution_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], name=op.f('fk_optimization_runs_prediction_run_id_prediction_runs')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_optimization_runs_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_runs'))
    )
    op.create_index(op.f('ix_optimization_runs_input_hash'), 'optimization_runs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_optimization_runs_manager_id'), 'optimization_runs', ['manager_id'], unique=False)
    op.create_table('player_gw_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('player_code', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.Integer(), nullable=False),
    sa.Column('opponent_team_code', sa.Integer(), nullable=False),
    sa.Column('was_home', sa.Boolean(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('minutes', sa.SmallInteger(), nullable=False),
    sa.Column('starts', sa.SmallInteger(), nullable=True),
    sa.Column('points', sa.SmallInteger(), nullable=False),
    sa.Column('goals', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('clean_sheets', sa.SmallInteger(), nullable=False),
    sa.Column('goals_conceded', sa.SmallInteger(), nullable=False),
    sa.Column('own_goals', sa.SmallInteger(), nullable=False),
    sa.Column('penalties_saved', sa.SmallInteger(), nullable=False),
    sa.Column('penalties_missed', sa.SmallInteger(), nullable=False),
    sa.Column('yellow_cards', sa.SmallInteger(), nullable=False),
    sa.Column('red_cards', sa.SmallInteger(), nullable=False),
    sa.Column('saves', sa.SmallInteger(), nullable=False),
    sa.Column('bonus', sa.SmallInteger(), nullable=False),
    sa.Column('bps', sa.SmallInteger(), nullable=False),
    sa.Column('dc', sa.SmallInteger(), nullable=True),
    sa.Column('cbi', sa.SmallInteger(), nullable=True),
    sa.Column('tackles', sa.SmallInteger(), nullable=True),
    sa.Column('recoveries', sa.SmallInteger(), nullable=True),
    sa.Column('price', sa.SmallInteger(), nullable=False),
    sa.Column('ownership_count', sa.BigInteger(), nullable=True),
    sa.Column('transfers_in', sa.BigInteger(), nullable=True),
    sa.Column('transfers_out', sa.BigInteger(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('raw_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('minutes between 0 and 130', name=op.f('ck_player_gw_stats_minutes_range')),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_player_gw_stats_fixture_id_fixtures')),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], name=op.f('fk_player_gw_stats_raw_snapshot_id_raw_snapshots')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_player_gw_stats_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_gw_stats')),
    sa.UniqueConstraint('season_id', 'fixture_id', 'player_code', name=op.f('uq_player_gw_stats_season_id_fixture_id_player_code'))
    )
    op.create_index(op.f('ix_player_gw_stats_fixture_id'), 'player_gw_stats', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_player_gw_stats_gw'), 'player_gw_stats', ['gw'], unique=False)
    op.create_index(op.f('ix_player_gw_stats_player_code'), 'player_gw_stats', ['player_code'], unique=False)
    op.create_index('ix_player_gw_stats_player_kickoff', 'player_gw_stats', ['player_code', 'kickoff_at'], unique=False)
    op.create_index(op.f('ix_player_gw_stats_season_id'), 'player_gw_stats', ['season_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('player_code', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('horizon', sa.SmallInteger(), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('n_fixtures', sa.SmallInteger(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('prob_2_plus', sa.Float(), nullable=False),
    sa.Column('prob_6_plus', sa.Float(), nullable=False),
    sa.Column('prob_10_plus', sa.Float(), nullable=False),
    sa.Column('prob_15_plus', sa.Float(), nullable=False),
    sa.Column('start_probability', sa.Float(), nullable=False),
    sa.Column('expected_minutes', sa.Float(), nullable=False),
    sa.Column('minutes_p10', sa.Float(), nullable=False),
    sa.Column('minutes_p50', sa.Float(), nullable=False),
    sa.Column('minutes_p90', sa.Float(), nullable=False),
    sa.Column('components_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calibration_bucket', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['prediction_runs.id'], name=op.f('fk_predictions_run_id_prediction_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('run_id', 'player_code', 'gw', name=op.f('uq_predictions_run_id_player_code_gw'))
    )
    op.create_index(op.f('ix_predictions_player_code'), 'predictions', ['player_code'], unique=False)
    op.create_index(op.f('ix_predictions_run_id'), 'predictions', ['run_id'], unique=False)
    op.create_table('team_gw_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.Integer(), nullable=False),
    sa.Column('was_home', sa.Boolean(), nullable=False),
    sa.Column('goals_for', sa.SmallInteger(), nullable=False),
    sa.Column('goals_against', sa.SmallInteger(), nullable=False),
    sa.Column('xg_for', sa.Float(), nullable=True),
    sa.Column('xg_against', sa.Float(), nullable=True),
    sa.Column('shots_proxy', sa.Float(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_team_gw_stats_fixture_id_fixtures')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_team_gw_stats_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_gw_stats')),
    sa.UniqueConstraint('season_id', 'fixture_id', 'team_code', name=op.f('uq_team_gw_stats_season_id_fixture_id_team_code'))
    )
    op.create_index(op.f('ix_team_gw_stats_season_id'), 'team_gw_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_gw_stats_team_code'), 'team_gw_stats', ['team_code'], unique=False)
    op.create_table('underlying_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('player_code', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_priority', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('xgc', sa.Float(), nullable=True),
    sa.Column('shots', sa.Float(), nullable=True),
    sa.Column('box_touches', sa.Float(), nullable=True),
    sa.Column('key_passes', sa.Float(), nullable=True),
    sa.Column('influence', sa.Float(), nullable=True),
    sa.Column('creativity', sa.Float(), nullable=True),
    sa.Column('threat', sa.Float(), nullable=True),
    sa.Column('set_piece_share', sa.Float(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_underlying_stats_fixture_id_fixtures')),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshots.id'], name=op.f('fk_underlying_stats_raw_snapshot_id_raw_snapshots')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_underlying_stats_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_underlying_stats')),
    sa.UniqueConstraint('season_id', 'fixture_id', 'player_code', 'source', name=op.f('uq_underlying_stats_season_id_fixture_id_player_code_source'))
    )
    op.create_index(op.f('ix_underlying_stats_player_code'), 'underlying_stats', ['player_code'], unique=False)
    op.create_index(op.f('ix_underlying_stats_season_id'), 'underlying_stats', ['season_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('manager_state_id', sa.String(length=80), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('expected_gain_vs_hold', sa.Float(), nullable=False),
    sa.Column('downside', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(length=16), nullable=False),
    sa.Column('stability', sa.String(length=16), nullable=True),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optimization_run_id', sa.String(length=80), nullable=True),
    sa.Column('prediction_run_id', sa.String(length=80), nullable=True),
    sa.Column('data_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.CheckConstraint("action_type in ('HOLD','TRANSFER','HIT','CHIP')", name=op.f('ck_recommendations_action_type')),
    sa.CheckConstraint('confidence between 0 and 1', name=op.f('ck_recommendations_confidence_range')),
    sa.ForeignKeyConstraint(['manager_state_id'], ['manager_state.id'], name=op.f('fk_recommendations_manager_state_id_manager_state')),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], name=op.f('fk_recommendations_optimization_run_id_optimization_runs')),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], name=op.f('fk_recommendations_prediction_run_id_prediction_runs')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_recommendations_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_gw'), 'recommendations', ['gw'], unique=False)
    op.create_index(op.f('ix_recommendations_manager_id'), 'recommendations', ['manager_id'], unique=False)
    op.create_table('transfer_candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('out_player_code', sa.Integer(), nullable=True),
    sa.Column('in_player_code', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('risk', sa.Float(), nullable=True),
    sa.Column('cost', sa.SmallInteger(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], name=op.f('fk_transfer_candidates_run_id_optimization_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_candidates'))
    )
    op.create_index(op.f('ix_transfer_candidates_run_id'), 'transfer_candidates', ['run_id'], unique=False)
    op.create_table('decision_journal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=80), nullable=False),
    sa.Column('followed', sa.String(length=16), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('realized_points', sa.Float(), nullable=True),
    sa.Column('realized_hold_points', sa.Float(), nullable=True),
    sa.Column('forecast_error', sa.Float(), nullable=True),
    sa.Column('review_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_decision_journal_recommendation_id_recommendations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_journal'))
    )
    op.create_index(op.f('ix_decision_journal_recommendation_id'), 'decision_journal', ['recommendation_id'], unique=False)
    op.create_table('recommendation_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=80), nullable=False),
    sa.Column('gw', sa.SmallInteger(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('out_player_code', sa.Integer(), nullable=True),
    sa.Column('in_player_code', sa.Integer(), nullable=True),
    sa.Column('captain_code', sa.Integer(), nullable=True),
    sa.Column('vice_captain_code', sa.Integer(), nullable=True),
    sa.Column('lineup_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chip_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_actions_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_actions'))
    )
    op.create_index(op.f('ix_recommendation_actions_recommendation_id'), 'recommendation_actions', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_actions_recommendation_id'), table_name='recommendation_actions')
    op.drop_table('recommendation_actions')
    op.drop_index(op.f('ix_decision_journal_recommendation_id'), table_name='decision_journal')
    op.drop_table('decision_journal')
    op.drop_index(op.f('ix_transfer_candidates_run_id'), table_name='transfer_candidates')
    op.drop_table('transfer_candidates')
    op.drop_index(op.f('ix_recommendations_manager_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_gw'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_underlying_stats_season_id'), table_name='underlying_stats')
    op.drop_index(op.f('ix_underlying_stats_player_code'), table_name='underlying_stats')
    op.drop_table('underlying_stats')
    op.drop_index(op.f('ix_team_gw_stats_team_code'), table_name='team_gw_stats')
    op.drop_index(op.f('ix_team_gw_stats_season_id'), table_name='team_gw_stats')
    op.drop_table('team_gw_stats')
    op.drop_index(op.f('ix_predictions_run_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_player_code'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_player_gw_stats_season_id'), table_name='player_gw_stats')
    op.drop_index('ix_player_gw_stats_player_kickoff', table_name='player_gw_stats')
    op.drop_index(op.f('ix_player_gw_stats_player_code'), table_name='player_gw_stats')
    op.drop_index(op.f('ix_player_gw_stats_gw'), table_name='player_gw_stats')
    op.drop_index(op.f('ix_player_gw_stats_fixture_id'), table_name='player_gw_stats')
    op.drop_table('player_gw_stats')
    op.drop_index(op.f('ix_optimization_runs_manager_id'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_input_hash'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_record_revisions_table_name'), table_name='record_revisions')
    op.drop_index(op.f('ix_record_revisions_natural_key'), table_name='record_revisions')
    op.drop_table('record_revisions')
    op.drop_table('prediction_runs')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_season_id'), table_name='players')
    op.drop_index(op.f('ix_players_code'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_player_snapshots_season_id'), table_name='player_snapshots')
    op.drop_index(op.f('ix_player_snapshots_player_code'), table_name='player_snapshots')
    op.drop_table('player_snapshots')
    op.drop_index(op.f('ix_manager_squad_state_id'), table_name='manager_squad')
    op.drop_table('manager_squad')
    op.drop_index(op.f('ix_fixtures_season_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_gw'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_teams_season_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_team_strength_season_id'), table_name='team_strength')
    op.drop_table('team_strength')
    op.drop_index(op.f('ix_raw_snapshots_source'), table_name='raw_snapshots')
    op.drop_index(op.f('ix_raw_snapshots_sha256'), table_name='raw_snapshots')
    op.drop_table('raw_snapshots')
    op.drop_index(op.f('ix_news_signals_season_id'), table_name='news_signals')
    op.drop_index(op.f('ix_news_signals_player_code'), table_name='news_signals')
    op.drop_table('news_signals')
    op.drop_index(op.f('ix_manager_transfers_manager_id'), table_name='manager_transfers')
    op.drop_table('manager_transfers')
    op.drop_index(op.f('ix_manager_state_state_hash'), table_name='manager_state')
    op.drop_index(op.f('ix_manager_state_season_id'), table_name='manager_state')
    op.drop_index(op.f('ix_manager_state_manager_id'), table_name='manager_state')
    op.drop_table('manager_state')
    op.drop_index(op.f('ix_manager_chips_manager_id'), table_name='manager_chips')
    op.drop_table('manager_chips')
    op.drop_index(op.f('ix_gameweeks_season_id'), table_name='gameweeks')
    op.drop_table('gameweeks')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_data_quality_events_source'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_severity'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_issue_code'), table_name='data_quality_events')
    op.drop_table('data_quality_events')
    op.drop_index(op.f('ix_backtest_decisions_backtest_id'), table_name='backtest_decisions')
    op.drop_table('backtest_decisions')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_notifications_manager_key'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_model_registry_one_production', table_name='model_registry', postgresql_where="status = 'production'")
    op.drop_index(op.f('ix_model_registry_status'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_model_name'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_table('manager_settings')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_request_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('data_snapshots')
    op.drop_index(op.f('ix_data_jobs_status'), table_name='data_jobs')
    op.drop_index(op.f('ix_data_jobs_source'), table_name='data_jobs')
    op.drop_index(op.f('ix_data_jobs_job_type'), table_name='data_jobs')
    op.drop_table('data_jobs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('artifact_blobs')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
