"""Generate docs/architecture/database-schema.md (Mermaid ER diagram) from the SQLAlchemy models.

The diagram is derived from ``fpl_storage.models`` — the same metadata Alembic migrations are
checked against — so it cannot drift from the schema (a test compares the committed file).

Usage: uv run python infra/scripts/schema_diagram.py
"""

from __future__ import annotations

from pathlib import Path

from fpl_storage.models import Base

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "architecture" / "database-schema.md"


def render() -> str:
    tables = sorted(Base.metadata.tables.values(), key=lambda t: t.name)
    lines = [
        "# Database schema",
        "",
        "Generated by `infra/scripts/schema_diagram.py` from `fpl_storage.models` "
        f"({len(tables)} tables). Do not edit by hand.",
        "",
        "```mermaid",
        "erDiagram",
    ]
    for t in tables:
        lines.append(f"  {t.name} {{")
        for c in t.columns:
            typ = type(c.type).__name__.lower()
            key = "PK" if c.primary_key else ("FK" if c.foreign_keys else "")
            lines.append(f"    {typ} {c.name}{(' ' + key) if key else ''}")
        lines.append("  }")
    rels = set()
    for t in tables:
        for fk in t.foreign_keys:
            rels.add((fk.column.table.name, t.name, fk.parent.name))
    for parent, child, col in sorted(rels):
        lines.append(f'  {parent} ||--o{{ {child} : "{col}"')
    lines += ["```", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}")
